### PR TITLE
fix(config): unable to load TS configs with `jiti@^2`

### LINKED ISSUE #601: Bug: TS config with latest `jiti` doesn't properly load
I'm working on moving the `eslint-plugin-eslint-plugin` project to TypeScript, and a supporting change is converting the `eslint-remote-tester`: https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/533.

Since we're already using `jiti` to run eslint with a TS config, we're using it for this use case as well.  I've found that the loading logic https://github.com/AriPerkkio/eslint-remote-tester/blob/master/packages/eslint-remote-tester/src/config/load.ts#L25-L30 isn't properly loading the config.  

When jiti returns the config, it returns a wrapped object with `default` property, rather than being the object that's exported as default.  

So, at this point in the config load: 
https://github.com/AriPerkkio/eslint-remote-tester/blob/master/packages/eslint-remote-tester/src/config/config.ts#L51

Image

The object is nested under `default`.

Image

I also, notice the `jiti.default` function is deprecated in the latest version.  So I'm not sure if maybe that's at play. 

Image

### PR DESCRIPTION
**Pull request by michaelfaith**
This change updates the load logic for TS Configs, to use jiti 2, if we've detected the new api, and falling back to the old api, otherwise.

I also updated the version of jiti to v2.  And added a new matrix for integration tests to run tests against both v1 and v2 or jiti. 

Lastly, I moved the config validation to be the first thing that happens in the cli, to catch cases where `repositories` wasn't defined in the config.  When config load was failing, the error was super ambiguous because it called `map` on `config.repositories` before running validation.  So, it took some digging to figure out what was wrong.

Closes #601

### CODE REVIEW

**Comment by michaelfaith** [comment]
Tested successfully ✅

File: packages/eslint-remote-tester/src/config/load.ts [hunk 1]
```diff
@@ -22,11 +27,20 @@ export const loadTSConfig = async (configPath: string) => {
...
     }
 
-    if (jiti) {
-        return jiti.default(import.meta.url, {
-            interopDefault: true,
-            esmResolve: true,
-        })(configPath);
+    if (jitiModule) {
+        // This is a good indicator that we're using v2+
+        if (jitiModule.createJiti) {
```
Comment (AriPerkkio) [inline packages/eslint-remote-tester/src/config/load.ts:32]: Perfect! 💯

File: packages/eslint-remote-tester/src/index.ts [hunk 2]
```diff
@@ -13,6 +13,8 @@ import logger from './progress-logger/index.js';
  * Results are written to ./eslint-remote-tester-results directory.
  */
 async function main() {
+    await validateConfig(config);
+
```
Comment (AriPerkkio) [inline packages/eslint-remote-tester/src/index.ts:17]: Oh this is good catch

**Review by AriPerkkio — APPROVED** [review]
Looks good, thanks so much @michaelfaith! 🙌

**Comment by AriPerkkio** [comment]
Fixed in https://github.com/AriPerkkio/eslint-remote-tester/releases/tag/v4.0.3
